syntax = "proto3";

package opticnode;

import "common.proto";
import "telemetry.proto";
import "modules.proto";

service OpticNode {
  rpc Ping(PingRequest)                        returns (PingResponse);
  rpc GetTelemetry(EmptyRequest)               returns (TelemetryResponse);
  rpc ExecuteCommand(ExecuteCommandRequest)    returns (ExecuteCommandResponse);
  rpc ListModules(EmptyRequest)                returns (ModuleListResponse);
  rpc StartModule(StartModuleRequest)          returns (RoleTaskResponse);
  rpc StopModule(StopModuleRequest)            returns (RoleTaskResponse);
  rpc ConfigureModule(ConfigureModuleRequest)  returns (RoleTaskResponse);
  rpc GetModuleLogs(ModuleLogsRequest)         returns (ModuleLogsResponse);
  rpc SubmitModuleJob(SubmitModuleJobRequest)  returns (SubmitModuleJobResponse);
}
